export const movies = [
  {
    poster_path: "/g1Z5HXYhVk0F188QeWRtDOWSdeG.jpg",
    adult: false,
    backdrop_path: "/5Zv5KmgZzdIvXz2KC3n0MyecSNL.jpg",
    id: 634528,
    vote_count: 71,
    vote_average: 6.7,
    title: "The Marksman",
    video: false,
    release_date: "2021-01-15",
    genre_ids: [28, 53, 80],
    original_language: "en",
    overview:
      "Jim Hanson’s quiet life is suddenly disturbed by two people crossing the US/Mexico border – a woman and her young son – desperate to flee a Mexican cartel. After a shootout leaves the mother dead, Jim becomes the boy’s reluctant defender. He embraces his role as Miguel’s protector and will stop at nothing to get him to safety, as they go on the run from the relentless assassins.",
    original_title: "The Marksman",
    popularity: 199.744,
    media_type: "movie",
  },
  {
    adult: false,
    backdrop_path: "/lA5fOBqTOQBQ1s9lEYYPmNXoYLi.jpg",
    genre_ids: [35, 878, 28, 12],
    id: 590223,
    original_language: "en",
    original_title: "Love and Monsters",
    overview:
      "Seven years after the Monsterpocalypse, Joel Dawson, along with the rest of humanity, has been living underground ever since giant creatures took control of the land. After reconnecting over radio with his high school girlfriend Aimee, who is now 80 miles away at a coastal colony, Joel begins to fall for her again. As Joel realizes that there’s nothing left for him underground, he decides against all logic to venture out to Aimee, despite all the dangerous monsters that stand in his way.",
    poster_path: "/r4Lm1XKP0VsTgHX4LG4syAwYA2I.jpg",
    release_date: "2020-10-16",
    title: "Love and Monsters",
    video: false,
    vote_average: 7.5,
    vote_count: 848,
    popularity: 121.85,
    media_type: "movie",
  },
  {
    vote_average: 8.3,
    overview:
      "In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.",
    release_date: "2021-03-24",
    id: 399566,
    adult: false,
    backdrop_path: "/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg",
    genre_ids: [28, 878],
    vote_count: 4396,
    original_language: "en",
    original_title: "Godzilla vs. Kong",
    poster_path: "/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg",
    video: false,
    title: "Godzilla vs. Kong",
    popularity: 5783.877,
    media_type: "movie",
  },
  {
    adult: false,
    backdrop_path: "/z7HLq35df6ZpRxdMAE0qE3Ge4SJ.jpg",
    genre_ids: [28, 12, 35, 14],
    original_language: "en",
    original_title: "Thunder Force",
    poster_path: "/279yOM4OQREL36B3SECnRxoB4MZ.jpg",
    video: false,
    vote_average: 5.8,
    id: 615678,
    overview:
      "In a world where supervillains are commonplace, two estranged childhood best friends reunite after one devises a treatment that gives them powers to protect their city.",
    release_date: "2021-04-09",
    vote_count: 269,
    title: "Thunder Force",
    popularity: 436.351,
    media_type: "movie",
  },
  {
    original_name: "The Nevers",
    origin_country: ["US"],
    genre_ids: [10765, 18],
    id: 80828,
    vote_count: 32,
    first_air_date: "2021-04-11",
    name: "The Nevers",
    vote_average: 8.8,
    original_language: "en",
    overview:
      'In the last years of Victoria\'s reign, London is beset by the "Touched": people — mostly women — who suddenly manifest abnormal abilities, some charming, some very disturbing. Among them are Amalia True, a mysterious, quick-fisted widow, and Penance Adair, a brilliant young inventor. They are the champions of this new underclass, making a home for the Touched, while fighting the forces of… well, pretty much all the forces — to make room for those whom history as we know it has no place.',
    poster_path: "/v6Xmj8Fy7ZruVTz3y2Po7O0TQh4.jpg",
    backdrop_path: "/6x8vW5utEZahp6V3sSWxCTW0mHW.jpg",
    popularity: 225.174,
    media_type: "tv",
  },
  {
    vote_average: 8.9,
    overview:
      "3000 years after the boy-god Nezha conquers the Dragon King then disappears in mythological times, he returns as an ordinary man to find his own path to becoming a true hero.",
    release_date: "2021-02-06",
    id: 663558,
    adult: false,
    backdrop_path: "/4PKfa0zltSrp1BJoLl8zfvYXaac.jpg",
    genre_ids: [16, 28, 14],
    vote_count: 30,
    original_language: "zh",
    original_title: "新神榜：哪吒重生",
    poster_path: "/6goDkAD6J3br81YMQf0Gat8Bqjy.jpg",
    video: false,
    title: "New Gods: Nezha Reborn",
    popularity: 35.507,
    media_type: "movie",
  },
  {
    title: "Mortal Kombat",
    vote_average: 7.8,
    overview:
      "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.",
    release_date: "2021-04-07",
    adult: false,
    backdrop_path: "/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg",
    vote_count: 36,
    genre_ids: [14, 28, 12],
    id: 460465,
    original_language: "en",
    original_title: "Mortal Kombat",
    poster_path: "/8yhtzsbBExY8mUct2GOk4LDDuGH.jpg",
    video: false,
    popularity: 838.669,
    media_type: "movie",
  },
  {
    adult: false,
    backdrop_path: "/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg",
    genre_ids: [28, 12, 14, 878],
    original_language: "en",
    original_title: "Zack Snyder's Justice League",
    poster_path: "/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg",
    video: false,
    vote_average: 8.6,
    id: 791373,
    overview:
      "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
    release_date: "2021-03-18",
    vote_count: 4882,
    title: "Zack Snyder's Justice League",
    popularity: 2851.189,
    media_type: "movie",
  },
  {
    vote_average: 9.3,
    overview:
      "A single dad and cosmetics brand owner figures out fatherhood on the fly when his strong-minded teen daughter moves in with him.",
    first_air_date: "2021-04-14",
    backdrop_path: "/hYfuxVs3ShpGRBHZFZdbsWedw4E.jpg",
    vote_count: 3,
    genre_ids: [35],
    name: "Dad Stop Embarrassing Me!",
    original_name: "Dad Stop Embarrassing Me!",
    origin_country: ["US"],
    poster_path: "/6uyHcbsxmJRUsFYL9qsbN3QwA7J.jpg",
    id: 119122,
    original_language: "en",
    popularity: 39.061,
    media_type: "tv",
  },
  {
    original_language: "en",
    poster_path: "/6kbAMLteGO8yyewYau6bJ683sw7.jpg",
    name: "The Falcon and the Winter Soldier",
    first_air_date: "2021-03-19",
    overview:
      "Following the events of “Avengers: Endgame”, the Falcon, Sam Wilson and the Winter Soldier, Bucky Barnes team up in a global adventure that tests their abilities, and their patience.",
    vote_count: 3707,
    vote_average: 7.8,
    original_name: "The Falcon and the Winter Soldier",
    origin_country: ["US"],
    backdrop_path: "/b0WmHGc8LHTdGCVzxRb3IBMur57.jpg",
    genre_ids: [10765, 10759, 18, 10768],
    id: 88396,
    popularity: 3536.187,
    media_type: "tv",
  },
  {
    adult: false,
    backdrop_path: "/bjjZXrP8PEdFeJkKERc62xlarMI.jpg",
    genre_ids: [18, 37],
    id: 581734,
    original_language: "en",
    original_title: "Nomadland",
    poster_path: "/66GUmWpTHgAjyp4aBSXy63PZTiC.jpg",
    video: false,
    title: "Nomadland",
    overview:
      "A woman in her sixties embarks on a journey through the western United States after losing everything in the Great Recession, living as a van-dwelling modern-day nomad.",
    release_date: "2020-12-26",
    vote_count: 508,
    vote_average: 7.6,
    popularity: 205.804,
    media_type: "movie",
  },
  {
    adult: false,
    backdrop_path: "/dEh93Ni98JWh7fmhD56ZlOFQmoT.jpg",
    genre_ids: [80, 18, 53],
    id: 606523,
    original_language: "ko",
    original_title: "낙원의 밤",
    overview:
      "A gangster tries to clean up his life to care for his sick sister and nephew. But someone targeting him accidentally kills them instead. In shock, he decides to take revenge.",
    poster_path: "/dYCWUAidqgakGETwZkfGxU7CWhL.jpg",
    release_date: "2020-09-03",
    title: "Night in Paradise",
    video: false,
    vote_average: 7.3,
    vote_count: 51,
    popularity: 52.975,
    media_type: "movie",
  },
  {
    backdrop_path: "/nRifrfdncHTRKUbk0MrAcuQmDFN.jpg",
    first_air_date: "2021-04-09",
    genre_ids: [18, 9648],
    id: 120462,
    name: "THEM",
    origin_country: ["US"],
    original_language: "en",
    original_name: "THEM",
    overview: "A limited anthology series that explores terror in America.",
    poster_path: "/bJw1VZ4ACt5TnAvJbHcprzgYc1E.jpg",
    vote_average: 8.3,
    vote_count: 14,
    popularity: 44.188,
    media_type: "tv",
  },
  {
    adult: false,
    backdrop_path: "/5NxjLfs7Bi07bfZCRl9CCnUw7AA.jpg",
    genre_ids: [878, 28, 12, 53],
    id: 412656,
    original_language: "en",
    original_title: "Chaos Walking",
    poster_path: "/9kg73Mg8WJKlB9Y2SAJzeDKAnuB.jpg",
    video: false,
    title: "Chaos Walking",
    overview:
      "Two unlikely companions embark on a perilous adventure through the badlands of an unexplored planet as they try to escape a dangerous and disorienting reality, where all inner thoughts are seen and heard by everyone.",
    release_date: "2021-02-24",
    vote_count: 350,
    vote_average: 7.4,
    popularity: 2168.951,
    media_type: "movie",
  },
  {
    poster_path: "/wFsrtlUpWJ4d4mo6UU1mLZbI75F.jpg",
    title: "Why Did You Kill Me?",
    video: false,
    vote_average: 10,
    overview:
      "The line between justice and revenge blurs when a devastated family uses social media to track down the people who killed 24-year-old Crystal Theobald.",
    release_date: "2021-04-14",
    adult: false,
    backdrop_path: "/oamFPL6EMqVNCfF152KiMfrWsXp.jpg",
    id: 810731,
    genre_ids: [99, 80],
    vote_count: 1,
    original_language: "en",
    original_title: "Why Did You Kill Me?",
    popularity: 64.067,
    media_type: "movie",
  },
  {
    overview:
      "Long ago, in the fantasy world of Kumandra, humans and dragons lived together in harmony. But when an evil force threatened the land, the dragons sacrificed themselves to save humanity. Now, 500 years later, that same evil has returned and it’s up to a lone warrior, Raya, to track down the legendary last dragon to restore the fractured land and its divided people.",
    release_date: "2021-03-03",
    adult: false,
    backdrop_path: "/7prYzufdIOy1KCTZKVWpjBFqqNr.jpg",
    vote_count: 2265,
    genre_ids: [16, 12, 14, 10751, 28],
    vote_average: 8.3,
    original_language: "en",
    original_title: "Raya and the Last Dragon",
    poster_path: "/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg",
    title: "Raya and the Last Dragon",
    video: false,
    id: 527774,
    popularity: 1671.917,
    media_type: "movie",
  },
  {
    adult: false,
    backdrop_path: "/h3weAFgg06GqchI2xDfufBgSFTj.jpg",
    genre_ids: [18],
    id: 600354,
    title: "The Father",
    vote_count: 280,
    vote_average: 8.3,
    video: false,
    release_date: "2021-02-26",
    overview:
      "A man refuses all assistance from his daughter as he ages and, as he tries to make sense of his changing circumstances, he begins to doubt his loved ones, his own mind and even the fabric of his reality.",
    original_title: "The Father",
    poster_path: "/uxWXW1YYQENSv7OzHB4Hds0bK3b.jpg",
    original_language: "en",
    popularity: 100.205,
    media_type: "movie",
  },
  {
    overview:
      "A botched store robbery places Wonder Woman in a global battle against a powerful and mysterious ancient force that puts her powers in jeopardy.",
    release_date: "2020-12-16",
    adult: false,
    backdrop_path: "/srYya1ZlI97Au4jUYAktDe3avyA.jpg",
    vote_count: 4828,
    genre_ids: [14, 28, 12],
    vote_average: 6.8,
    original_language: "en",
    original_title: "Wonder Woman 1984",
    poster_path: "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
    title: "Wonder Woman 1984",
    video: false,
    id: 464052,
    popularity: 1032.187,
    media_type: "movie",
  },
  {
    adult: false,
    backdrop_path: "/dIR8HSH2Rkfye23fzAOh5sJHhtS.jpg",
    genre_ids: [28, 18, 53],
    id: 808228,
    original_language: "en",
    original_title: "Night of the Sicario",
    poster_path: "/rgFewciOc5lFXVoUDuboN87vbwO.jpg",
    video: false,
    title: "Night of the Sicario",
    overview:
      "Taylor is forced to hide the young daughter of a Colombian woman in witness protection who will be testifying against a powerful drug cartel in Federal Court, as ruthless sicarios aim to hunt them down.",
    release_date: "2021-04-16",
    vote_count: 4,
    vote_average: 6.8,
    popularity: 45.814,
    media_type: "movie",
  },
  {
    overview:
      "When an engineer learns of a mysterious, impenetrable fortress hidden under The Bank of Spain, he joins a crew of master thieves who plan to steal the legendary lost treasure locked inside while the whole country is distracted by Spain's World Cup Final. With thousands of soccer fans cheering in the streets, and security forces closing in, the crew have just minutes to pull off the score of a lifetime.",
    release_date: "2021-03-04",
    adult: false,
    backdrop_path: "/2ZjxT6orLC4v3zff1QNkKL7S16.jpg",
    vote_count: 68,
    genre_ids: [80, 28, 53],
    vote_average: 7.1,
    original_language: "en",
    original_title: "Way Down",
    poster_path: "/eSlazQmwqtlRIbmZ72xBGr0MEFH.jpg",
    title: "The Vault",
    video: false,
    id: 630004,
    popularity: 56.809,
    media_type: "movie",
  },
];
